server:
  port: 8080

logging:
  config: classpath:logback.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ruiji?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false # MySQL\u5728\u9AD8\u7248\u672C\u9700\u8981\u6307\u660E\u662F\u5426\u8FDB\u884CSSL\u8FDE\u63A5 \u89E3\u51B3\u5219\u52A0\u4E0A &useSSL=false
    name: demo
    username: root
    password: root
    # \u4F7F\u7528druid\u6570\u636E\u6E90
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  thymeleaf:
    # 模板的模式
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    # 这个开发配置为false，避免改了模板还要重启服务器
    cache: false
    prefix: classpath:/templates/


# mybatis-plus\u76F8\u5173\u914D\u7F6E
mybatis-plus:
  # xml\u626B\u63CF\uFF0C\u591A\u4E2A\u76EE\u5F55\u7528\u9017\u53F7\u6216\u8005\u5206\u53F7\u5206\u9694\uFF08\u544A\u8BC9 Mapper \u6240\u5BF9\u5E94\u7684 XML \u6587\u4EF6\u4F4D\u7F6E\uFF09
  mapper-locations: classpath:**/*Mapper.xml
  configuration:
    #        \u65E5\u5FD7
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  # \u4EE5\u4E0B\u914D\u7F6E\u5747\u6709\u9ED8\u8BA4\u503C,\u53EF\u4EE5\u4E0D\u8BBE\u7F6E
  global-config:
    #\u4E3B\u952E\u7C7B\u578B  0:"\u6570\u636E\u5E93ID\u81EA\u589E", 1:"\u7528\u6237\u8F93\u5165ID",2:"\u5168\u5C40\u552F\u4E00ID (\u6570\u5B57\u7C7B\u578B\u552F\u4E00ID)", 3:"\u5168\u5C40\u552F\u4E00ID UUID";
    id-type: 0
    #\u5B57\u6BB5\u7B56\u7565 0:"\u5FFD\u7565\u5224\u65AD",1:"\u975E NULL \u5224\u65AD"),2:"\u975E\u7A7A\u5224\u65AD"
    field-strategy: 2
    #\u9A7C\u5CF0\u4E0B\u5212\u7EBF\u8F6C\u6362
    db-column-underline: true
    #\u5237\u65B0mapper \u8C03\u8BD5\u795E\u5668
    refresh-mapper: false