
server:
  port: 8080
  servlet:
    #    context-path: /api
    application-display-name: demo

spring:
  application:
    name: demo
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/study_xj?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false # MySQL\u5728\u9AD8\u7248\u672C\u9700\u8981\u6307\u660E\u662F\u5426\u8FDB\u884CSSL\u8FDE\u63A5 \u89E3\u51B3\u5219\u52A0\u4E0A &useSSL=false
    name: demo
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

management:
  security:
    enabled: false


#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xj.demo.pojo
  configuration:
    map-underscore-to-camel-case: true